            <?php
                
                /*
                    This shows how to load specific fields from a record in the database.
                    1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
                    2) You can then just use the get(fieldname) to pull specific data from the table.
                    3) If you have a field named news_id, then it becomes getNewsId, etc.
                */
                
                //$image = Mage::getModel('imageuploader/imageuploader')->load(1);
                //echo $image->getNewsId().'<br />';
                //echo $image->getTitle().'<br />';
               // echo $image->getContent().'<br />';
                //echo $image->getStatus().'<br />';
		//echo '<img src="'.$this->getBaseUrl().'media/'.$image->getFilename().'" alt="" />';
		$collection = Mage::getModel("imageuploader/imageuploader")->getCollection();
		$pageName=$this->getLayout()->getBlock('head')->getTitle();
		if($pageName=='Testimonials') {$pageName='Our Clients';}
		$collection->getSelect()->where('status=1 AND category=?',$pageName);
		$collection->setOrder('RAND()', '');
		$images = $collection->load();
		$i=1;
		echo '<ul>';
		foreach ($images as $item){
		echo '<li><a href="'.$this->getBaseUrl().'media/thumblarge/'.$item->getFilename().'" title="'.$item->getTitle().'"><img src="'.$this->getBaseUrl().'media/thumb/'.$item->getFilename().'" alt="" /></a></li>';
		$i = $i+1;
		if($i>5) break;
		}                
		echo '</ul>';


                /*$collection = Mage::getModel('imageuploader/imageuploader')->getCollection()->addAttributeToSort('RAND()','');
		$i=1;
		foreach ($collection as $item) {
		if($item->getCategory()==Mage::getSingleton('cms/page')->getTitle()){
			echo '<img src="'.$this->getBaseUrl().'media/thumb/'.$item->getFilename().'" alt="" />';
			$i = $i+1;
			}
		if($i>5) break;
                }*/
                /*
                    This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
 					Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

               */
                /*
                $object = $this->getImageuploader();
                echo 'id: '.$object['test_id'].'<br/>';
				echo 'title: '.$object['title'].'<br/>';
				echo 'content: '.$object['content'].'<br/>';
				echo 'status: '.$object['status'].'<br/>';
                */            
            
            
                /*
                    This shows how to load multiple rows in a collection and save a change to them.
                    1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
                    2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
                */
                /*
                $i = 0;
                
                $collection = Mage::getModel('imageuploader/imageuploader')->getCollection();
                $collection->setPageSize(5);
                $collection->setCurPage(2);
                $size = $collection->getSize();
                $cnt = count($collection);
                foreach ($collection as $item) {
                    $i = $i+1;
                    $item->setTitle($i);
                    echo $item->getTitle();
                }

                $collection->walk('save');
                */
                
                /*
                    This shows how to load a single record and save a change.
                    1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
                    2) Call the save() function only on a single record.
                */
                /*
                $object = Mage::getModel('imageuploader/imageuploader')->load(1);
                $object->setTitle('This is a changed title');
                $object->save();
				*/

            ?> 
